config/routes.rb
Rails.application.routes.draw do
#  get '/run_seed', to: 'application#run_seed'
  get "/dashboard", to: "dashboards#show", as: :dashboard
  resources :enrollments
  resources :courses do
    member do
      get :progress
    end
    collection do
      get :analytics
    end
  end
  root "welcome#index"

  get "users/profile"
  devise_for :users
  get "profile", to: "users#profile", as: :user_profile

  # Health check y configuración PWA
  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/shared/_footer.html.erb
<footer class="footer" style="padding: 1rem 0;">
    <div class="container" style="max-width: 70%; margin: auto;">
      <div class="columns is-vcentered">
        <!-- Logo y dirección -->
        <div class="column is-3">
          <%= link_to root_path do %>
            <%= image_tag "Logo2ctrn.png", alt: "Inicio", width: "30", height: "30" %>
          <% end %>
          <p class="has-text-white-ter">Tocornal 601, Santiago<br>Chile</p>
        </div>

        <!-- Íconos de redes sociales -->
        <div class="column is-3 has-text-centered">
          <div class="buttons">
            <a class="button is-dark" href="#"><i class="fab fa-facebook-f has-text-white"></i></a>
            <a class="button is-dark" href="#"><i class="fab fa-linkedin-in has-text-white"></i></a>
            <a class="button is-dark" href="#"><i class="fab fa-twitter has-text-white"></i></a>
            <a class="button is-dark" href="#"><i class="fab fa-instagram has-text-white"></i></a>
          </div>
        </div>

        <!-- Etiquetas o enlaces de navegación -->
        <div class="column is-3 has-text-centered">
          <nav class="level is-mobile">
            <% ["Label", "Label", "Label", "Label", "Label"].each do |label| %>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading has-text-white-ter"><%= label %></p>
                </div>
              </div>
            <% end %>
          </nav>
        </div>

        <!-- Texto de derechos -->
        <div class="column is-3 has-text-right">
            <p class="has-text-white-ter">Designed by 2C © 2024</p>
        </div>
      </div>

      <!-- Enlaces legales -->
      <div class="columns is-centered">
        <div class="column is-narrow has-text-centered">
          <p class="has-text-white-ter">
            <a href="#" class="has-text-white-ter">Privacy</a> |
            <a href="#" class="has-text-white-ter">Terms</a> |
            <a href="#" class="has-text-white-ter">Legal</a>
          </p>
        </div>
      </div>
    </div>
  </footer>

app/views/shared/_navbar_bulma.html.erb
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="container" style="max-width: 70%; margin: auto;">
    <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
        <%= image_tag "Logo2ctrn.png", alt: "Inicio", width: "30", height: "30" %>
      <% end %>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="<%= root_path %>">Inicio</a>

        <% if user_signed_in? %>
          <!-- Menú de cursos -->
          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">Cursos</a>

            <div class="navbar-dropdown">
              <% if current_user.instructor? %>
                <%= link_to "Crear Curso", new_course_path, class: "navbar-item" %>
                <%= link_to "Ver Cursos", courses_path, class: "navbar-item" %>
                <%= link_to "Analítica de Cursos", "/courses/analytics", class: "navbar-item" %>
              <% elsif current_user.estudiante? %>
                <%= link_to "Explorar Cursos", courses_path, class: "navbar-item" %>
                <%= link_to "Mis Inscripciones", dashboard_path, class: "navbar-item" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <% if user_signed_in? %>
            <p>Bienvenido a Plantilla, <%= current_user.nombre %></p>
            <div class="buttons">
              <!-- Enlace para modificar perfil -->
              <%= link_to 'Modificar Perfil', edit_user_registration_path, class: 'button is-link' %>
              <%= button_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'button is-light' %>
            </div>
          <% else %>
            <div class="buttons">
              <%= link_to 'Regístrate', new_user_registration_path, class: 'button is-primary' %>
              <%= link_to 'Iniciar sesión', new_user_session_path, class: 'button is-light' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {
      // Add a click event on each of them
      $navbarBurgers.forEach(el => {
        el.addEventListener('click', () => {
          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');
        });
      });
    }
  });
</script>